# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/stable_diffusion_playground',
                'doc_host': 'https://davorrunje.github.io',
                'git_url': 'https://github.com/davorrunje/stable_diffusion_playground',
                'lib_path': 'stable_diffusion_playground'},
  'syms': {'stable_diffusion_playground.stable_diffusion': {}}}
